import './globals.css'
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "../../components/base/header"
import Footer from "../../components/base/footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>
        <Header />
        <main className="flex flex-col items-center place-content-center gap-20 m-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
